### ISSUE TITLE
log_parser nodes stop processing messages after cluster is in "yellow" state

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#89]
We had an extended outage where the elasticsearch nodes were in the "yellow" state for a few hours.

After the elasticsearch nodes had returned to green, the log_parser failed to start processing messages again (even though the monit `log_parser` & `elasticsearch` processes were reported as being `running`, and there were no error messages (or anything else) in the log_parser logs (`/var/vcap/sys/log/log_parser/log_parser.*.log`).

A `monit restart log_parser` restored processing.

**Comment by dpb587** [comment]
I think we should upgrade to elasticsearch/1.4.0 first and see if that helps with this.

I've briefly looked into this before and it seems like elasticsearch hangs onto connections longer than it should during certain cluster discovery operations which makes logstash hang and not retry.

**Comment by mrdavidlaing** [comment]
I'm not convinced that its a problem with elasticsearch, since restarting logstash seems to be what fixed it.

However, I agree that we should do the upgrade first before investigating further.

For posterity; this is what the logs looked like around this incident:

```
root@3b40f3d3-fbbd-4e0e-94b0-963544ea2fe1:~# monit summary
The Monit daemon 5.2.4 uptime: 5d 18h 25m 

Process 'log_parser'                running
Process 'log_parser-elasticsearch'  running
Process 'logsearch-logs'            running
Process 'logsearch-metrics'         running
System 'system_3b40f3d3-fbbd-4e0e-94b0-963544ea2fe1' running
root@3b40f3d3-fbbd-4e0e-94b0-963544ea2fe1:~# monit restart log_parser
root@3b40f3d3-fbbd-4e0e-94b0-963544ea2fe1:~# tail -f /var/vcap/sys/log/log_parser/*.log
==> /var/vcap/sys/log/log_parser/elasticsearch.requests.log <==
{"time":"2014-11-11T13:07:58.116Z","starttime":"2014-11-11T13:07:58.107Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":6009,"duration":9,"year":"2014","month":"11","day":"11","hour":"13","minute":"07","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:07:59.135Z","starttime":"2014-11-11T13:07:59.120Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":11748,"duration":15,"year":"2014","month":"11","day":"11","hour":"13","minute":"07","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:00.061Z","starttime":"2014-11-11T13:08:00.031Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":31176,"duration":30,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:00.153Z","starttime":"2014-11-11T13:08:00.145Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":5775,"duration":8,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:01.193Z","starttime":"2014-11-11T13:08:01.176Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":12755,"duration":17,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:02.233Z","starttime":"2014-11-11T13:08:02.215Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":18458,"duration":18,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:03.266Z","starttime":"2014-11-11T13:08:03.252Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":13075,"duration":14,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:04.312Z","starttime":"2014-11-11T13:08:04.297Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":15652,"duration":15,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:05.379Z","starttime":"2014-11-11T13:08:05.354Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":23323,"duration":25,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:08:06.371Z","starttime":"2014-11-11T13:08:06.346Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":52382,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":27907,"duration":25,"year":"2014","month":"11","day":"11","hour":"13","minute":"08","dow":"Tue","cluster":"live-logsearch"}

==> /var/vcap/sys/log/log_parser/elasticsearch.stderr.log <==
Exception in thread "elasticsearch[log_parser-1b/1][generic][T#24]" java.lang.NullPointerException
    at org.elasticsearch.action.bulk.TransportBulkAction.setResponseFailureIfIndexMatches(TransportBulkAction.java:178)
    at org.elasticsearch.action.bulk.TransportBulkAction.access$100(TransportBulkAction.java:65)
    at org.elasticsearch.action.bulk.TransportBulkAction$1.onFailure(TransportBulkAction.java:137)
    at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$2.run(TransportAction.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

==> /var/vcap/sys/log/log_parser/elasticsearch.stdout.log <==
[2014-11-11 13:14:02,681][INFO ][discovery.zen            ] [log_parser-1b/1] failed to send join request to master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}], reason [org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.]
[2014-11-11 13:14:35,689][INFO ][discovery.zen            ] [log_parser-1b/1] failed to send join request to master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}], reason [org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.]
[2014-11-11 13:15:08,696][INFO ][discovery.zen            ] [log_parser-1b/1] failed to send join request to master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}], reason [org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.]
[2014-11-11 13:15:41,705][INFO ][discovery.zen            ] [log_parser-1b/1] failed to send join request to master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}], reason [org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.]
[2014-11-11 13:16:14,710][INFO ][discovery.zen            ] [log_parser-1b/1] failed to send join request to master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}], reason [org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.]
[2014-11-11 13:16:33,150][INFO ][discovery.zen            ] [log_parser-1b/1] master_left [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}], reason [do not exists on master, act as master failure]
[2014-11-11 13:16:34,942][INFO ][cluster.service          ] [log_parser-1b/1] detected_master [api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}, added {[log_parser-1b/0][hIAajGwRSYK8FlBOelPDRw][c59bb745-a486-4ab4-957e-0675b09e803d][inet[/10.13.24.6:9300]]{job_name=log_parser-1b, job_index=0, data=false, master=false},[elasticsearch_eu-west-1b/1][OFh0yz5mTRGUpd7kRyMyHw][30b5f755-8fee-4117-b942-5fcb8012f862][inet[/10.13.24.11:9300]]{job_name=elasticsearch_eu-west-1b, job_index=1, max_local_storage_nodes=1, master=true},[log_parser-1b/2][Dzt4f3VRT6y1jsCQzkvuVQ][a67d9693-6208-46cb-bb38-ba9b07d82b62][inet[/10.13.24.7:9300]]{job_name=log_parser-1b, job_index=2, data=false, master=false},[elasticsearch_eu-west-1b/0][fLY0DSkRRDC5Qiw9fh2C_w][0f6070cb-4164-42ee-b9c0-57a1c1cae667][inet[/10.13.24.10:9300]]{job_name=elasticsearch_eu-west-1b, job_index=0, max_local_storage_nodes=1, master=true},[elasticsearch_eu-west-1a/0][eSm5KrkgTYKToXWU_cPd9Q][3b705c71-fb6b-4cda-807f-f474ba70c626][inet[/10.13.8.22:9300]]{job_name=elasticsearch_eu-west-1a, job_index=0, max_local_storage_nodes=1, master=false},[log_parser-1c/1][kd7BTh3dTHy0L9K7y2jE_Q][bb4d0b05-c36a-4c94-b7ad-495ae4cf5c89][inet[/10.13.40.11:9300]]{job_name=log_parser-1c, job_index=1, data=false, master=false},[log_parser-1c/0][LjTA1-SXT-uchz1p9GpQUw][dee52965-2c13-4449-b603-2fb71ba29e51][inet[/10.13.40.10:9300]]{job_name=log_parser-1c, job_index=0, data=false, master=false},[elasticsearch_eu-west-1c/0][4pl1dV8FSsi6jPTqStEskQ][bf39e181-48ed-4b49-a66c-92b583aac2c6][inet[/10.13.40.13:9300]]{job_name=elasticsearch_eu-west-1c, job_index=0, max_local_storage_nodes=1, master=false},[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true},[api/1][YeSmBgP2TAuzQqpnx5MVlg][07351c76-77ec-4982-a43c-d1c521774bb8][inet[/10.13.17.2:9300]]{job_name=api, job_index=1, data=false, max_local_storage_nodes=1, master=true},[log_parser-1a/0][V-QDcvISSImab0BnJztNkw][50ceef6f-497e-473b-9327-7061e39f2d75][inet[/10.13.8.18:9300]]{job_name=log_parser-1a, job_index=0, data=false, master=false},[elasticsearch_eu-west-1c/1][LF8w0068RK64tYzvRRymMg][e4c6b2e1-2cb8-4b34-8fe7-2354c028c644][inet[/10.13.40.14:9300]]{job_name=elasticsearch_eu-west-1c, job_index=1, max_local_storage_nodes=1, master=false},[log_parser-1a/1][qNbpMXdWRJaaOo_IB6ciCg][43a17f3f-031b-4912-86a8-5c713a3246b4][inet[/10.13.8.19:9300]]{job_name=log_parser-1a, job_index=1, data=false, master=false},}, reason: zen-disco-receive(from master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}])
[2014-11-11 13:16:38,937][INFO ][cluster.service          ] [log_parser-1b/1] added {[elasticsearch_eu-west-1a/1][4EHVDHRMS0iGZ2C9ylYbaw][b4c8d9b4-dafb-4616-9668-3f3d1455226a][inet[/10.13.8.23:9300]]{job_name=elasticsearch_eu-west-1a, job_index=1, max_local_storage_nodes=1, master=false},}, reason: zen-disco-receive(from master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}])
[2014-11-11 13:44:47,962][INFO ][cluster.service          ] [log_parser-1b/1] removed {[elasticsearch_eu-west-1c/0][4pl1dV8FSsi6jPTqStEskQ][bf39e181-48ed-4b49-a66c-92b583aac2c6][inet[/10.13.40.13:9300]]{job_name=elasticsearch_eu-west-1c, job_index=0, max_local_storage_nodes=1, master=false},}, reason: zen-disco-receive(from master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}])
[2014-11-11 13:44:55,989][INFO ][cluster.service          ] [log_parser-1b/1] removed {[elasticsearch_eu-west-1c/1][LF8w0068RK64tYzvRRymMg][e4c6b2e1-2cb8-4b34-8fe7-2354c028c644][inet[/10.13.40.14:9300]]{job_name=elasticsearch_eu-west-1c, job_index=1, max_local_storage_nodes=1, master=false},}, reason: zen-disco-receive(from master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}])

==> /var/vcap/sys/log/log_parser/log_parser.stderr.log <==

==> /var/vcap/sys/log/log_parser/log_parser.stdout.log <==
{:timestamp=>"2014-11-11T13:07:53.711000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:53.651Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:07:53.807000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:53.597Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:07:54.345000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:54.272Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:07:54.713000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:54.629Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:07:54.717000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:54.379Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:07:55.387000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:55.295Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:07:55.660000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:55.488Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:07:57.288000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:07:57.086Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:08:02.497000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:08:02.376Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:08:08.863000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:08:08.704Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}

==> /var/vcap/sys/log/log_parser/undrain.log <==

==> /var/vcap/sys/log/log_parser/log_parser.stdout.log <==
{:timestamp=>"2014-11-11T13:49:15.196000+0000", :message=>"Using milestone 2 input plugin 'redis'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.236000+0000", :message=>"Using milestone 2 output plugin 'elasticsearch_http'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.274000+0000", :message=>"Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.284000+0000", :message=>"Using milestone 1 filter plugin 'alter'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.400000+0000", :message=>"Using milestone 1 filter plugin 'syslog_pri'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.455000+0000", :message=>"Using milestone 2 filter plugin 'kv'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.473000+0000", :message=>"Using milestone 2 filter plugin 'json'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.573000+0000", :message=>"Using milestone 2 filter plugin 'csv'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:15.698000+0000", :message=>"Using milestone 1 filter plugin 'translate'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones", :level=>:warn}
{:timestamp=>"2014-11-11T13:49:28.797000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:49:28.198Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}

==> /var/vcap/sys/log/log_parser/elasticsearch.requests.log <==
{"time":"2014-11-11T13:49:29.612Z","starttime":"2014-11-11T13:49:29.594Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":41221,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":9914,"duration":18,"year":"2014","month":"11","day":"11","hour":"13","minute":"49","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:49:41.211Z","starttime":"2014-11-11T13:49:29.956Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":41221,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":4719,"duration":11255,"year":"2014","month":"11","day":"11","hour":"13","minute":"49","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:49:45.602Z","starttime":"2014-11-11T13:49:41.566Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":41221,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":30446,"duration":4036,"year":"2014","month":"11","day":"11","hour":"13","minute":"49","dow":"Tue","cluster":"live-logsearch"}

==> /var/vcap/sys/log/log_parser/log_parser.stdout.log <==
{:timestamp=>"2014-11-11T13:49:47.098000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:49:37.761Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:49:47.339000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:49:37.891Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:49:47.339000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:49:37.893Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}

==> /var/vcap/sys/log/log_parser/elasticsearch.requests.log <==
{"time":"2014-11-11T13:49:48.994Z","starttime":"2014-11-11T13:49:46.313Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":41221,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":13214,"duration":2681,"year":"2014","month":"11","day":"11","hour":"13","minute":"49","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:49:49.775Z","starttime":"2014-11-11T13:49:49.732Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":41221,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":30588,"duration":43,"year":"2014","month":"11","day":"11","hour":"13","minute":"49","dow":"Tue","cluster":"live-logsearch"}
{"time":"2014-11-11T13:49:50.065Z","starttime":"2014-11-11T13:49:50.055Z","localaddr":"127.0.0.1","localport":9200,"remoteaddr":"127.0.0.1","remoteport":41221,"scheme":"http","method":"POST","path":"/_bulk","querystr":"replication=sync","code":200,"status":"OK","size":7642,"duration":10,"year":"2014","month":"11","day":"11","hour":"13","minute":"49","dow":"Tue","cluster":"live-logsearch"}

==> /var/vcap/sys/log/log_parser/log_parser.stdout.log <==
{:timestamp=>"2014-11-11T13:49:51.629000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:49:42.923Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}
{:timestamp=>"2014-11-11T13:49:51.713000+0000", :message=>"Failed parsing date from field", :field=>"@timestamp", :value=>"2014-11-11T13:49:42.921Z", :exception=>#<TypeError: cannot convert instance of class org.jruby.RubyTime to class java.lang.String>, :level=>:warn}

==> /var/vcap/sys/log/log_parser/elasticsearch.stdout.log <==
[2014-11-11 13:49:53,032][INFO ][cluster.service          ] [log_parser-1b/1] removed {[elasticsearch_eu-west-1b/0][fLY0DSkRRDC5Qiw9fh2C_w][0f6070cb-4164-42ee-b9c0-57a1c1cae667][inet[/10.13.24.10:9300]]{job_name=elasticsearch_eu-west-1b, job_index=0, max_local_storage_nodes=1, master=true},}, reason: zen-disco-receive(from master [[api/0][MYjXLtTPS7qi5Vdy2SJL3g][1f6dfccd-c887-48f9-8035-76e8a9d5c540][inet[/10.13.17.1:9300]]{job_name=api, job_index=0, data=false, max_local_storage_nodes=1, master=true}])
```

**Comment by dpb587** [comment]
I was proposing that logstash was blocking on a TCP connection waiting for elasticsearch to respond, but elasticsearch had lost track of what to do with that connection in the midst of its health/node shuffles so logstash was just waiting. Restarting logstash would have killed that connection along with the process, so new connections after restart would be made to elasticsearch in a stable state. I tested this once by manually killing the logstash<->elasticsearch TCP connection instead of restarting logstash and logstash emitted an exception but returned to message parsing.

Like I said, it's just a theory, but I don't think it being fixed by a restarted logstash disproves it. Regardless, I agree; revisit post-1.4.0.

**Comment by dpb587** [comment]
Haven't seen this happen in a long time now, so closing. Going to assume something between the major elasticsearch upgrades and changes in how we're pushing data through has fixed it. We can reopen later if that's not the case.
